
name: Suggestify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:

    name: Suggestify

    runs-on: ubuntu-latest
    steps:

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Checkout code
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Suggestify
        run: python ./run.py    